[package]
name = "feoh_matchup_tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.10.0", features = ["image", "tokio"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
image = { version = "0.24.6", features = ["png"]}
strum = "0.25"
strum_macros = "0.25"
reqwest = { version = "0.11", features = ["rustls-tls"], default-features = false}
bytes = "1"